### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [socialshares/buttons#1]
Could you implement something like this for every social media?

<pre><code>
window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title) + ':%20'  + encodeURIComponent(document.URL))
</code></pre>

In order to automatically preload the Title of the shared page? 
Thanks

**Comment by sunnysingh** [comment]
@Karlheinzniebuhr: Makes sense, I will set the current page title as the default if it's not provided. I will update when I get a chance.

**Comment by Karlheinzniebuhr** [comment]
thanks! I forgot to mention that it has to be inside the [onlick() event](http://www.w3schools.com/jsref/event_onclick.asp) otherwise browsers won't execute it for security reasons..

**Comment by sunnysingh** [comment]
@Karlheinzniebuhr: The included JS file provides popup functionality through `window.open()` already, I just don't do anything special aside from opening the `href` of each button. Refactoring the code to not require a lot of configuration and simply rely on the JS is on the roadmap but I kept it simple for now.

**Comment by sunnysingh** [comment]
@Karlheinzniebuhr: I added default URLs if the `href` attribute is empty or non-existent. I definitely want to do a future release where configuration can be done through `data-*` attributes or something, but this is a start.
