### ISSUE TITLE
".bower.json" missing "main" files section

### ISSUE THREAD

**Issue by vbaidak** [socialshares/buttons#4]
Hi!
Thank you for your library!

Here is a description of the issue:

**.bower.json** file does not contain **main** section.

As a result **bower-concat** is not able to add and process **socialshares** files automatically.

In order to make **bower-concat** to see **socialshares** I had to add the following section into **bower-concat** configuration:
`
mainFiles: {
              'socialshares': ['build/js/buttons.js', 'build/js/buttons.jquery.js']
            },
`

I suggest fixing this issue by simply declaring the **main** section right in the **socialshares** root **.bower.json** file:

`
"main": [
    "build/js/buttons.js",
    "build/js/buttons.jquery.js",
    "build/js/buttons.css",
    "build/js/buttons-no-icons.css"
  ],
`

Thanks in advance!

**Comment by sunnysingh** [comment]
Hey @vbaidak, sorry for the very late response. I just released v2 of socialshares so I'm not really planning on maintaining v1 anymore. I made sure to add a "main" file in the Bower config in v2. It looks like you have a solution in place for your project, but if need be feel free to open a pull request. Let me know if I can go ahead and close out this issue.
