### ISSUE TITLE
Add support for mobile applications

### ISSUE THREAD

**Issue by vbaidak** [socialshares/buttons#5]
Hi!

I would like to ask you about adding support for mobile applications, e.g. when user clicks the **share** button, the library check if this application is installed on the device, and if so, delegate this _share_ call to app, otherwise make it in browser.

Thanks!

**Comment by sunnysingh** [comment]
Hi @vbaidak, sorry for the very late response. From my testing, share links are intercepted on Android (worked for Twitter, Reddit, and Google+ for me, but not Facebook). I assume this behavior is the same on iOS, but you or someone else can hopefully confirm.

The other thing is that I've recently released v2 of socialshares and I don't really plan on maintaining v1 anymore. You're free to continue using v1, but I think in v2 I can look into using the new [Web Share API](https://developers.google.com/web/updates/2016/10/navigator-share). Although, it looks like it doesn't allow sharing to a specific app at the moment, but just open the generic share dialog on mobile.
